#!/bin/bash

function CranialNerveII()
{
	OPTIND=1

	usage="Usage: CranialNerveII [option]
	\n\t-i, --cameraid\t\tSet camera id, Defualt is 0
	\nExample:
	\n\tCranialNerveII -i 0\t\t\t Run CranialNerveII with camera id 0.
	\n\tCranialNerveII --cameraid 1\t\t Run CranialNerveII with camera id 1."

	# default value of camera id is 0
	cameraid=0

	# accept -i/--cameraid as option
	OPTS=`getopt -o i:h --long cameraid:,help -n ${0##*/} -- "$@"`

	eval set -- "$OPTS"

	# read option
	while true; 
	do
		case $1 in
			-i|--cameraid)
				echo "Set camera id to ${2}";
				cameraid=$2;
				shift 2
				;;
			-h|--help)
				echo -e $usage;
				OPTIND=1;
				return
				;;
			--) shift; break ;;
		esac
	done
	# reset option id
	OPTIND=1

	# set ros parameter
	COMMAND='rosparam set /vision_manager/cameraID ${cameraid}'
	eval $COMMAND

	echo -e -n "\033]0; CranialNerveII \007" 

	# run node
	rosrun newbie_hanuman CranialNerveII 

}

function CranialNerveIIMonitor()
{
	OPTIND=1

	usage="Usage: CranialNerveIIMonitor
	\n\tNo options
	\nExample:
	\n\tCranialNerveIIMonitor\t\t\t Run CranialNerveIIMonitor."

	OPTS=`getopt -o h --long help -n ${0##*/} -- "$@"`

	eval set -- "$OPTS"

	# read option
	while true; 
	do
		case $1 in
			-h|--help)
				echo -e $usage;
				OPTIND=1;
				return
				;;
			--) shift; break ;;
		esac
	done
	OPTIND=1

	echo -e -n "\033]0; CranialNerveIIMonitor \007" 
	
	# run node
	rosrun newbie_hanuman CranialNerveIIMonitor 
}


function OccipitalLobe()
{
	OPTIND=1

	usage="Usage: OccipitalLobe [options]
	\n\t-m, --module\t\t File path for vision module used in OccipitalLobe and KinematicLobe.
	\nExample:
	\n\tOccipitalLobe -m /some/file/path\t\t\t Run OccipitalLobe."

	# default of path is ''
	vision_module_path=''

	# accept only -m/--module
	OPTS=`getopt -o m:h --long module:,help -n ${0##*/} -- "$@"`

	eval set -- "$OPTS"

	# read ooption
	while true; 
	do
		case $1 in
			-m|--module)
				echo "Set vision_module_path to ${2}";
				vision_module_path=$2
				shift 2
				;;
			-h|--help)
				echo -e $usage;
				OPTIND=1;
				return;
				;;
			--) shift; break ;;
		esac
	done
	# reset option id
	OPTIND=1

	# if not set -m/--module dont do anything
	# otherwise set ros paameter
	if [ -z $vision_module_path ]
	then
		:
	else
		COMMAND='rosparam set /vision_manager/vision_module_path ${vision_module_path}'
		eval $COMMAND
	fi

	echo -e -n "\033]0; OccipitalLobe \007" 

	# run node
	rosrun newbie_hanuman OccipitalLobe 

}

export -f CranialNerveII
export -f OccipitalLobe
export -f CranialNerveIIMonitor